Serve files through proxy server
TortugaPower/bookplayer-api pull request #15
Opened 2023-11-03 03:18 UTC by ynunezaguirre

2023-11-03 07:06 UTC, harrisi reviewed
Overall it seems like it's working great. I think the main thing that would be important would be the added headers I mentioned. Nice work!

2023-11-03 07:06 UTC, harrisi commented on development.env.template
> +APP_VERSION=2023-10-30
It's not super important, but we should decide how/when this gets updated. It could be a GitHub action or git hook for whenever a feature is added behind a date, or something.

2023-11-03 07:06 UTC, harrisi commented on package.json
> +    "@types/cookie-parser": "^1.4.4",
It doesn't look like we're using `cookie-parser` anywhere. Do we need this?

2023-11-03 07:06 UTC, harrisi commented on src/api/StorageRouter.ts
> +    router.get('/general/:sufix/:key', middleWareInit, (req, res, next) =>
I don't love this. I think we should stick to a single path, `/:key`, since this path is only needed because of the bucket layout for thumbnails, which is an implementation detail we don't need to share with clients. I'm not really sure what the best solution is, though.

This also provides a strange duplication of behavior, where if a file is located at `a/foo.mp3`, you can do `GET /storage/a%2Ffoo.mp3` or `GET /storage/general/%2Fa/foo.mp3`. Which nobody should do, but it's odd that it's available.

I don't think there is an issue where you can read files from other users or anything, but I could be missing an attack vector.

I also don't hate this. I don't know. I do like that it leaves options for things other than thumbnails, but I'm not sure what else we would have. Maybe we could just have this be `/image/:key`?

2023-11-03 07:06 UTC, harrisi commented on src/api/StorageRouter.ts
> +    router.get('/general/:sufix/:key', middleWareInit, (req, res, next) =>
Also, 'sufix' is used several places, but it should be 'suffix'. Not sure if we want to keep using it in general, but if we do, we should fix that before we push it.

2023-11-03 07:06 UTC, harrisi commented on src/controllers/AdminController.ts
> +            folderKey: `${user.email}/`,
I'm not sure where or how this endpoint is used, but maybe this should include thumbnails as well?

2023-11-03 07:06 UTC, harrisi commented on src/controllers/StorageController.ts
> +    const { range } = req.headers;
There are a number of headers which clients would like to send that `GetClientObject` accepts, such as `If-None-Match` and `If-Modified-Since`, probably `If-Match`, and `If-Unmodified-Since` as well. I'm not sure if any of the others would be useful for us.

2023-11-03 07:06 UTC, harrisi commented on src/controllers/StorageController.ts
> +  public async getProxyFile(req: IRequest, res: IResponse): Promise<IResponse> {
Can these functions be combined, maybe with some changes to the `/storage` endpoint?

2023-11-03 07:06 UTC, harrisi commented on src/controllers/StorageController.ts
> +    const { sufix, key } = req.params;
We may also want some of the headers I mentioned before here.

2023-11-03 07:06 UTC, harrisi commented on src/api/middlewares/auth.ts
> +  req.app_version =
We might want to move this logic to a function, since we could add a table with clients and versions that are pinned to an API date, so we don't need to send this header forever. Its intent is to be used for new/changing/breaking functionality, but reducing the need to send it is ideal.

2023-11-03 07:06 UTC, harrisi commented on src/services/LibraryService.ts
> +          let fileUrlExpireIn = null;
We probably don't want to send this back if we're using the new storage url.

We actually don't need to send it ever, I don't think. The iOS app doesn't seem to use it, and the pre-signed url includes it in the query param anyway. @GianniCarlo can you confirm?

2023-11-03 07:06 UTC, harrisi commented on src/services/SubscriptionService.ts
> +      const appleIds = aliases;
Is this needed? Can't we just pass `aliases || [original_app_user_id]` to `getUserByAppleID`?

2023-11-03 12:27 UTC, GianniCarlo commented on src/services/LibraryService.ts
> +          let fileUrlExpireIn = null;
yup, right now the iOS app does not use it

2023-11-03 16:51 UTC, harrisi commented
There are a couple other things I was thinking about, that maybe should be separate PRs.

The main one is rate limiting. I think that can be middleware for the app as a whole, but there should be stricter limitations for file egress. I think that would be easy enough to enable, maybe using redis to keep track of how many requests/minute or bytes/minute easily.

One thing to keep in mind is that every client (currently iOS and web) make extensive use of byte ranges, so for storage access, it should be based on the number of bytes requested, not individual requests. This should be roughly the size of the file per hour or something, although for large files that could still be a lot of data, and for small files it doesn't necessarily make sense to limit it that much. Maybe something like limit each file access to the greater of 1GiB or the size of the file, so a 100MiB file could be downloaded 10 times in an hour, but a 10GiB file can be downloaded once per hour.

The other is older client access. Can we use a similar method as this to send `api.tortugapower.com/storage/presigned/a.mp3` (or something) to older clients so we can still enable the rate limiting? The issue currently is that these endpoints require credentials (which I think is good), but older iOS clients can't be updated to add credentials. Could we send something like that (`/storage/presigned/:key`) and have that route not enforce credentials? That's definitely another PR, but I'd like to get to a point where clients never have to see the raw storage url.

There may also be a way to limit pre signed urls based on how many times it's accessed? Or amount of data egress? Then you could also limit sending the urls to the client. That might be tricky, but also potentially worth it.

Happy holidays! :)

2023-11-03 22:45 UTC, GianniCarlo commented
I agree with rate limiting, though for the byte ranges I would argue that it would be better to do the minimum between 1GB (possibly less) or the file size in an hour, as the byte ranges is basically for streaming, so I don't think a user should surpass 1GB when listening through an hour, as audiobooks that are around the 1GB range, are usually around 20-30 hours long, so even if they're on 4x speed, they can't realistically listen to it in under an hour. When it's a request to download the entire file, we can limit that differently 

Re older client access, hmmmm not sure to be honest, I mean I do want to get rid of the S3 urls as fast as we can, but without the header auth token, how would the backend map `/storage/presigned/:key` to the proper user's file? or the key would have the user's email at the beginning to route to the proper bucket? if that's the case I think although the S3 urls are shareable and open, it's at least a hassle to get them, having a way to request any file from any user, it's a bit too open, though I may be missing something here in how it would work @harrisi? 🤔

2023-11-04 00:38 UTC, harrisi commented
> I agree with rate limiting, though for the byte ranges I would argue that it would be better to do the minimum between 1GB (possibly less) or the file size in an hour, as the byte ranges is basically for streaming, so I don't think a user should surpass 1GB when listening through an hour, as audiobooks that are around the 1GB range, are usually around 20-30 hours long, so even if they're on 4x speed, they can't realistically listen to it in under an hour. When it's a request to download the entire file, we can limit that differently

The numbers I picked were just for easy math, and your numbers make more sense. The main considerations when picking a rate would be making sure it's possible to download a folder (even two or three larger files can get to the 1GiB limit), and how we handle multiple clients. You can limit per file, per user, or per client, and they all have different reasonable rate limits.

I think the best way to handle this is to not enable any limits yet, but get everything set up for it and do some analysis of what average usage is like for average users. Or just set it to limit at whatever rate, but don't actually deny requests yet, just log it (send an email to us or have some dashboard for us or something), and see where a reasonable line is. We could start rather low and increase it until it seems like a good medium. Lots of things we can do here to fine tune it.

> Re older client access, hmmmm not sure to be honest, I mean I do want to get rid of the S3 urls as fast as we can, but without the header auth token, how would the backend map `/storage/presigned/:key` to the proper user's file? or the key would have the user's email at the beginning to route to the proper bucket? if that's the case I think although the S3 urls are shareable and open, it's at least a hassle to get them, having a way to request any file from any user, it's a bit too open, though I may be missing something here in how it would work @harrisi? 🤔

One way to do it is when a user requests `GET /library?sign=true` (with `relativePath` or not, doesn't matter), we do the whole presign deal and everything as normal, but instead of sending it back to the client, we send `{..., "url": "https://api.tortugapower.com/storage/presigned/${uuid}", ...}`, store a tuple of `(uuid, presignedUrl)` in redis with an expiration equal to `expires_in`, and when a client requests `/storage/presigned/${uuid}`, we just make the request to the presigned url that's mapped to that uuid, forward the headers, and stream the response back. There might be an easier way to handle that, but the idea will probably be similar.

2023-11-20 01:03 UTC, ynunezaguirre commented on development.env.template
> +APP_VERSION=2023-10-30
I added in scripts/env.js a few lines to update the env param. This script is executed every time a deployment is performed

2023-11-20 01:05 UTC, ynunezaguirre commented on src/controllers/AdminController.ts
> +            folderKey: `${user.email}/`,
👌🏻 done

2023-11-20 01:08 UTC, ynunezaguirre commented on package.json
> +    "@types/cookie-parser": "^1.4.4",
removed

2023-11-20 01:09 UTC, ynunezaguirre commented on src/controllers/StorageController.ts
> +  public async getProxyFile(req: IRequest, res: IResponse): Promise<IResponse> {
rigth, works better right now they are combined.

2023-11-20 03:56 UTC, harrisi requested changes
There's just the one issue with head case-sensitivity that needs to be fixed, and a little cleanup.

I haven't tested it yet though, but everything else looks good to me! :)

2023-11-20 03:56 UTC, harrisi commented on scripts/env.js
> +    const formattedDate =
We can use `const formattedDate = currentDate.toISOString().split('T')[0];` or `currentDate.toISOString().substring(0, 10);` to make this a little cleaner.

2023-11-20 03:56 UTC, harrisi commented on src/controllers/StorageController.ts
> +      res.status(400).json({ error: 'Error fetching the file' });
This feels like it should be a 500 still.

2023-11-20 03:56 UTC, harrisi commented on src/types/user.ts
> +  'If-unmodified-since' = 'IfUnmodifiedSince',
The `I` should be lowercase here.

2023-11-20 03:56 UTC, harrisi commented on src/controllers/StorageController.ts
> +        const validValue = req.headers[key];
This should lowercase the key before comparing, since our enum assumes things are lowercase.

2023-11-20 03:56 UTC, harrisi commented on src/types/user.ts
> +  'If-unmodified-since' = 'IfUnmodifiedSince',
I actually think we should only use the `-` variants, as those are what are defined by the standard. We should still compare the headers from the client case-insensitively by lowercasing them, but I don't think we should accept non-standard headers unless there's a good reason to.

2023-11-20 05:51 UTC, harrisi commented on development.env.template
> +APP_VERSION=2023-10-30
Hm, I'm not sure if that's ideal. If a deployment just changes some implementation details that don't change anything from a client's perspective, I'm not sure we want to update the app version. The `APP_VERSION` should really only be updated when there's some breaking change, I think.

I'm a fan of git hooks for things like this, where it updates the APP_VERSION before pushing to remote. But we could also use a GitHub action to comment whenever the changes include some string or something. Probably easiest to do that and add a function to make the string to search for consistent.

I think for now we don't need to update the app version in a script, and we can figure out the details of this later.

2023-11-23 00:04 UTC, ynunezaguirre commented
@harrisi i pushed some fixes, right now the changes are in staging if you want to try them :)

2023-11-23 04:12 UTC, harrisi requested changes
Found an issue with the response headers. Sorry I didn't notice this before :(

2023-11-23 04:12 UTC, harrisi commented on src/services/LibraryService.ts
> +          ? `${process.env.PROXY_FILE_URL}/_thumbnail/${encodeURIComponent(
There's an extra `/` after the proxy file url here.

2023-11-23 04:12 UTC, harrisi commented on src/services/S3Service.ts
> +      return response.Body as Readable;
I think this is dropping some of the headers and status code. It's not clear to me from the docs, but I think you need to just return the response as a whole? I'm not really sure.

The issue is that the client needs to get the 206 or 304 (or others, but these are the main codes I'm missing) to properly stream and handle caching, and I'm also not getting headers such as `Accept-Ranges` and `Content-Length`.

2023-11-23 13:37 UTC, ynunezaguirre commented on src/services/LibraryService.ts
> +          ? `${process.env.PROXY_FILE_URL}/_thumbnail/${encodeURIComponent(
im trying to see the extra `/`  but i cant 😅 , the proxy file url would be something like `http://localhost:5000/v1/storage` without the `/` at the end.

2023-11-23 14:30 UTC, harrisi commented on src/services/LibraryService.ts
> +          ? `${process.env.PROXY_FILE_URL}/_thumbnail/${encodeURIComponent(
Oh, I think I misunderstood. Since the s3 bucket layout is `email_thumbnail` I thought this was mapping to `email/_thumbnail` by mistake, but I see that's not the case. Oops!

2023-11-23 15:03 UTC, ynunezaguirre commented on src/services/S3Service.ts
> +      return response.Body as Readable;
yeah, it wasnt sending the headers from the s3 object response, i just put the headers that are part of the s3 library object. 

`'Accept-Ranges',
    'Content-Length',
    'Content-Range',
    'Content-Type',
    'Etag',
    'Last-Modified'`

and send the status code that comes from the s3 too 👌🏻

2023-11-24 04:28 UTC, harrisi commented on src/services/S3Service.ts
> +        'Last-Modified': `${response.LastModified}`,
This throws when any of these are absent. I _think_ the only time that happens is `ContentRange` being absent, because `Range` isn't sent in the request, but it looks like the library defines all of them as optional.

2023-11-24 21:57 UTC, harrisi commented
I think we also need to set `Cross-Origin-Resource-Policy` to `cross-origin` for the storage endpoint. It's currently set to `same-origin`. I'm not sure if there are any other CORS-related headers that are going to cause issues, but I don't think so.

2023-11-28 14:23 UTC, ynunezaguirre commented on src/services/S3Service.ts
> +        'Last-Modified': `${response.LastModified}`,
yeah, the problem was content range, i put all of them in a conditional to prevent any undefined values.

2023-11-28 14:27 UTC, ynunezaguirre commented
you can try it in the staging server right now, let me know if this is ok to squash all the fix commits to one before merge the pull request.

2023-11-28 20:17 UTC, harrisi commented
I don't think this got pushed to staging yet. I'm still seeing the old same-origin value for CORP. I'm not sure how you're pushing to staging so I don't want to mess with it.

2023-11-28 20:25 UTC, ynunezaguirre commented
Please try again now. I missed something in the morning 😅

2023-11-28 20:31 UTC, harrisi commented
Also, I think the CORP setting is from helmet and can be modified there. Or maybe it's modifying it after you're setting it? The default for helmet is to set it to `same-origin`.

2023-11-28 20:57 UTC, harrisi commented
So far things seem to be working! :) Feel free to squash whatever you need.

2023-12-02 06:30 UTC, harrisi commented
I realized there's another change that would improve how this works on web. There's an issue currently with how I'm fetching mp4 metadata, where I have to attempt to read past the end of the remote file to know when I'm done getting metadata. Since the request is a CORS request, the only headers my application can see are [CORS-safelisted response headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header). The main thing that I'm missing due to that is the `Content-Range` header, which should give me the length of the file so I don't attempt to read past it.

2023-12-08 15:36 UTC, ynunezaguirre commented
@harrisi i made a small change and pushed it to staging, when you have time please try to verify if that resolve the issue with the Content-Range header in the cors request.

2023-12-09 08:11 UTC, harrisi commented
@ynunezaguirre Nice! :) Looks like I'm getting the content range in the response.

So far I think everything is good. I think we may want to modify how some of the CORS stuff is handled at some point, but for now things are working.

We should make sure nothing in the app is broken by this, but I don't see why it would since it's behind an opt-in header (@GianniCarlo, if you could confirm). Related to that, I think we should add a table for client pinning. The web app, for example, should always get at least this version of the api. I figure adding a table of (client, version, api_version) would be easy. But I don't think we need to figure that out right now.

I'll be happy to see this promoted to production soon. :)

2023-12-09 16:41 UTC, GianniCarlo commented
I can confirm the app as it is right now is working when pointing to staging 😁, all good on my end to put this on production 👌

2023-12-13 17:58 UTC, ynunezaguirre commented
@GianniCarlo @harrisi.  I took Ian some ideas to create a middleware to handle the version related to the request origin. In the apple clients table there is a new column where it is specified which version that client works with. This is saved in the Redis the first request if it doesn't exists previously. 

The Accept-Version header remains a priority in case the client sends it. 
In the case of the mobile application  shouldn't be a problem because it does not send the origin header so they use the first versión by default and when gianni wants to use a new version he just has to send the 'Accept-Version' header with the version or 'latest' value.

In this way what I would be missing is a function for the administrator to be able to change and refresh the cache of a client version, i will do it soon, right now the change is pushed to staging.

2023-12-13 19:15 UTC, harrisi commented
Excellent! I only had a minute to skim over the changes but they look good to me so far.

I'm not able to test it yet but it looks promising.

2024-01-03 02:00 UTC, GianniCarlo commented
@yamilnunez I thought this PR was already merged/deployed to prod, for the new changes about the S3 let's branch off master and create a new PR so it's not mixed with this one

2024-01-04 14:31 UTC, merged